//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_Center
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProvaiderOrder
    {
        public int id { get; set; }
        public Nullable<int> ProvaiderOrderid { get; set; }
        public Nullable<int> Productidid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<double> count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProvaiderOrder ProvaiderOrder { get; set; }
    }
}
